import PDFDocument from 'pdfkit';
import fs from 'fs';
import path from 'path';
import getStream from 'get-stream';
import { ScanResult, Vulnerability} from './types';

function formatDate(iso?: string){
    const d = iso ? new Date(iso) : new Date();
    return d.toLocaleString('en-GB', { timeZone: 'UTC', year: 'numeric', month: 'short', day: 'numeric', hour: '2-digit', minute: '2-digit' }) + ' UTC';
}
export async function generatePDFReportPdfBuffer(scanResult: ScanResult, scanId?: string ): Promise<Buffer> {
    const doc = new PDFDocument({margin:40, size:'A4'});

    const stream = doc.pipe(require('stream').PassThrough());

    try{
        const logoPath = path.join(process.cwd(), 'public', 'logo.png');
        if(fs.existsSync(logoPath)){
            doc.image(logoPath, 40, 30, {width: 120});
        }
    } catch(e){
        console.error('Error loading logo image:', e);
    }

    doc.fontSize(20).text('TEKTON Scan Report',0, 40, {align: 'center'});
    doc.moveDown(2);

    doc.fontSize(12).fillColor('black');
    doc.text(`Scan ID: ${scanResult.scanId || 'N/A'}`, {align: 'right'});
    doc.text(`Scan date: ${formatDate(scanResult.scanDate)}`, {align: 'right'});
    doc.moveDown();

    doc.fillColor('black').fontSize(14).text('Scanned URL', {underline: true});
    doc.fontSize(12).text(scanResult.target || 'N/A');
    doc.moveDown(0.8);

    if (scanResult.results.discoveredEndpoints && scanResult.results.discoveredEndpoints.length) {
        doc.fontSize(12).text(`Crawled pages (${scanResult.results.discoveredEndpoints.length}):`, { underline: true });
        const list = scanResult.results.discoveredEndpoints.slice(0, 10);
        list.forEach((u) => doc.fontSize(10).text(' • ' + u, { indent: 10 }));
        if (scanResult.results.discoveredEndpoints.length > 10) {
          doc.fontSize(10).text(` • ... and ${scanResult.results.discoveredEndpoints.length - 10} more`, { indent: 10 });
        }
        doc.moveDown(0.5);
      }
    
      if (scanResult.results.ports && scanResult.results.ports.length) {
        doc.fontSize(12).text(`Open ports:`, { underline: true });
        scanResult.results.ports.forEach(p => doc.fontSize(10).text(` • ${p.port} ${p.service ? `(${p.service})` : ''}`, { indent: 10 }));
        doc.moveDown(0.5);
      }
    
      // Vulnerabilities section
      const vulns = scanResult.results.vulnerabilities || [];
      doc.addPage(); // start vulnerabilities on new page to keep it readable
      doc.fontSize(16).text(`Vulnerabilities (${vulns.length})`, { underline: true });
      doc.moveDown(0.5);
    
      if (vulns.length === 0) {
        doc.fontSize(12).text('No vulnerabilities found.', { continued: false });
      } else {
        vulns.forEach((v: Vulnerability, idx: number) => {
          // Box header
          const sev = (v.severity || 'info').toUpperCase();
          doc.fontSize(12).fillColor('black').text(`${idx + 1}. ${v.title} `, { continued: false });
          doc.fontSize(10).fillColor('gray').text(`Severity: ${sev}    Type: ${v.type || 'N/A'}${v.location ? '    Location: ' + v.location : ''}`, { indent: 10 });
          doc.moveDown(0.2);
          doc.fontSize(11).fillColor('black').text('Description:', { indent: 10 });
          doc.fontSize(10).text(truncate(v.description || '—', 800), { indent: 18 });
          doc.moveDown(0.2);
          doc.fontSize(11).text('How to fix:', { indent: 10 });
          doc.fontSize(10).text(v.fix || 'No remediation provided.', { indent: 18 });
          doc.moveDown(0.6);
    
          // page break if near end
          if (doc.y > 720) {
            doc.addPage();
          }
        });
      }
    
      // Footer
      doc.moveDown(1);
      doc.fontSize(9).fillColor('gray').text('Generated by TEKTON Vulnerability Scanner — For authorized use only.', { align: 'center' });
    
      doc.end();
    
      // collect buffer
      const buffer = await getStream.buffer(stream);
      return buffer;
    }
    
    function truncate(text: string, max = 400) {
      if (!text) return text;
      return text.length > max ? text.slice(0, max - 3) + '...' : text;
    
}