import { NextRequest, NextResponse } from 'next/server';
import { getScan } from '@/app/lib/db';

/**
 * GET /api/export
 * Export scan results (simulated PDF generation)
 */
export async function GET(request: NextRequest) {
  try {
    const { searchParams } = new URL(request.url);
    const scanId = searchParams.get('scan_id');
    const format = searchParams.get('format') || 'pdf';

    if (!scanId) {
      return NextResponse.json(
        { error: 'scan_id is required' },
        { status: 400 }
      );
    }

    const scan = getScan(scanId);

    if (!scan) {
      return NextResponse.json(
        { error: 'Scan not found' },
        { status: 404 }
      );
    }

    // In a real app, this would generate actual PDF using libraries like jsPDF or pdfkit
    // For now, we'll return a formatted text report

    const report = generateTextReport(scan);

    if (format === 'json') {
      return NextResponse.json({
        scan_id: scan.scanId,
        target: scan.target,
        status: scan.status,
        started_at: scan.startedAt,
        completed_at: scan.completedAt,
        results: scan.results
      });
    }

    // Return as downloadable file
    return new NextResponse(report, {
      headers: {
        'Content-Type': 'text/plain',
        'Content-Disposition': `attachment; filename="tekton-scan-${scanId}.txt"`
      }
    });

  } catch (error) {
    console.error('Error exporting scan:', error);
    return NextResponse.json(
      { error: 'Internal server error' },
      { status: 500 }
    );
  }
}

function generateTextReport(scan: any): string {
  let report = '';

  report += '═══════════════════════════════════════════════════════\n';
  report += '               TEKTON SECURITY SCAN REPORT              \n';
  report += '═══════════════════════════════════════════════════════\n\n';

  report += `Scan ID: ${scan.scanId}\n`;
  report += `Target: ${scan.target}\n`;
  report += `Status: ${scan.status.toUpperCase()}\n`;
  report += `Started: ${scan.startedAt.toISOString()}\n`;
  if (scan.completedAt) {
    report += `Completed: ${scan.completedAt.toISOString()}\n`;
  }
  report += '\n';

  if (scan.results?.ports && scan.results.ports.length > 0) {
    report += '───────────────────────────────────────────────────────\n';
    report += '  OPEN PORTS\n';
    report += '───────────────────────────────────────────────────────\n';
    scan.results.ports.forEach((port: any) => {
      report += `  • Port ${port.port} (${port.service})\n`;
    });
    report += '\n';
  }

  if (scan.results?.technologies && scan.results.technologies.length > 0) {
    report += '───────────────────────────────────────────────────────\n';
    report += '  TECHNOLOGIES DETECTED\n';
    report += '───────────────────────────────────────────────────────\n';
    scan.results.technologies.forEach((tech: any) => {
      const version = tech.version ? ` v${tech.version}` : '';
      report += `  • ${tech.name}${version} [${tech.category}]\n`;
    });
    report += '\n';
  }

  if (scan.results?.vulnerabilities && scan.results.vulnerabilities.length > 0) {
    report += '───────────────────────────────────────────────────────\n';
    report += '  VULNERABILITIES FOUND\n';
    report += '───────────────────────────────────────────────────────\n\n';
    scan.results.vulnerabilities.forEach((vuln: any, index: number) => {
      report += `  [${index + 1}] ${vuln.title}\n`;
      report += `      Severity: ${vuln.severity.toUpperCase()}\n`;
      report += `      Type: ${vuln.type.toUpperCase()}\n`;
      report += `      Description: ${vuln.description}\n`;
      if (vuln.location) {
        report += `      Location: ${vuln.location}\n`;
      }
      if (vuln.recommendation) {
        report += `      Recommendation: ${vuln.recommendation}\n`;
      }
      report += '\n';
    });
  } else {
    report += '───────────────────────────────────────────────────────\n';
    report += '  ✓ NO VULNERABILITIES FOUND\n';
    report += '───────────────────────────────────────────────────────\n\n';
  }

  report += '═══════════════════════════════════════════════════════\n';
  report += '           End of Report - Generated by TEKTON          \n';
  report += '═══════════════════════════════════════════════════════\n';

  return report;
}
